<?php

namespace Database\Seeders;

use App\Models\Item;
use App\Models\Tenant;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Seed the default items (repuestos) for every tenant.
     *
     * Running it again does not duplicate items.
     */
    public function run(): void
    {
        $items = [
            '173355' => 'SEGURO PARA MICROMETRO CLAMP HANDLE MITUTOYO',
            '173356' => 'TOPE DE TRINQUETE PARA MICROMETRO MITUTOYO',
            '173357' => 'PASADOR DE PIVOTE PARA TORQUIMETRO CDI',
            '173358' => 'REMACHE PASADOR DE PIVOTE PARA TORQUIMETRO CDI',
            '173359' => 'KIT DE REPARACION TORQUIMETRO MICROMETRICO 3/8" CDI',
            '173360' => 'ANILLO DE FRICCIÓN DE 3/8" P/PISTOLA IMPACTO MILWAUKEE',
            '173361' => 'O-RING FRONTAL P/PISTOLA IMPACTO MILWAUKEE',
            '173362' => 'YUNQUE CUADRANTE DE 3/8" P/PISTOLA IMPACTO MILWAUKEE',
            '173363' => 'O- RING INTERNO P/PISTOLA IMPACTO MILWAUKEE',
            '173364' => 'CONJUNTO ROTOR TAPA TRASERA P/PISTOLA IMPACTO MILWAUKEE',
            '173365' => 'MODULO ELECTRONICO P/PISTOLA IMPACTO MILWAUKEE',
            '173366' => 'KIT CONJUNTO DISPARADOR Y ELÉCTRICO P/PISTOLA IMPACTO INGRERSOLL',
            '173367' => 'KIT MOTOR SIN ESCOBILLAS P/PISTOLA IMPACTO INGERSOLL',
            '173368' => 'KIT DE MECANISMO DE IMPACTO P/PISTOLA IMPACTO INGERSOLL',
            '173369' => 'KIT RETENEDOR DE DADO 3/8\'\' P/PISTOLA IMPACTO INGERSOLL',
            '173370' => 'KIT RETENEDOR DE DADO 1/2\'\' P/PISTOLA IMPACTO INGERSOLL',
            '173371' => 'LUZ LED FRONTAL P/PISTOLA IMPACTO INGERSOLL',
            '173372' => 'TARJETA DE CONTROL P/TALADRO MILWAUKEE',
            '173373' => 'TORNILLO DE MANDRIL M8.0 X 1 LH T-40 P/TALADRO MILWAUKEE',
            '173374' => 'PLACA DE DESGASTE P/PISTOLA IMPACTO INGERSOLL',
            '173385' => 'KIT DE PIEZAS DE ENTRADA P/PISTOLA IMPACTO INGERSOLL',
            '173386' => 'KIT DE PUESTA A PUNTO P/PISTOLA IMPACTO INGERSOLL',
            '173387' => 'CONJUNTO DE CARCASA DEL HUSILLO P/AMOLADORA MILWAUKEE',
            '173388' => 'LUZ LED P/AMOLADORA MILWAUKEE',
            '173389' => 'ENSAMBLAJE ELECTRÓNICO P/AMOLADORA MILWAUKEE',
            '173390' => 'KIT PALETAS JUEGO DE 5 P/AMOLADORA INGERSOLL',
            '173391' => 'RODAMIENTO TRASERO P/AMOLADORA INGERSOLL',
            '173392' => 'PLACA TRASERA P/AMOLADORA INGERSOLL',
            '173393' => 'PLACA FRONTAL P/AMOLADORA INGERSOLL',
            '173394' => 'RODAMIENTO DELANTERO P/AMOLADORA INGERSOLL',
            '173395' => 'JUEGO DE PIÑÓN DE ENGRANAJE (PARA 5102MAX)',
            '173396' => 'CARCASA DE AGUJAS P/ESCARIADOR INGERSOLL',
            '173397' => 'CALZA DE ALINEACION P/ESCARIADOR INGERSOLL',
            '173398' => 'CLIP DE RETENEDOR P/ESCARIADOR INGERSOLL',
            '173399' => 'PORTAAGUJAS P/ESCARIADOR INGERSOLL',
            '173400' => 'RESORTE P/ESCARIADOR INGERSOLL',
            '173401' => 'KIT DE PALETAS JUEGO DE 5 P/MOTOR NEUMATICO INGERSOLL',
            '173402' => 'RODAMIENTO DEL ROTOR DELANTERO P/MOTOR NEUMATICO INGERSOLL',
            '173403' => 'KIT ENGRANAJES PLANETARIO DE HUSILLO P/MOTOR NEUMATICO INGERSOLL',
            '173404' => 'RODAMIENTO DE ENGRANAJE PLANETARIO P/MOTOR NEUMATICO INGERSOLL',
            '173405' => 'PIÑON DE ROTOR PARA RATIO 012 O 015 P/MOTOR NEUMATICO INGERSOLL',
            '173406' => 'PIÑON DEL ROTOR PARA RATIO 004, 188 O 151 P/MOTOR NEUMATICO INGERSOLL',
            '173407' => 'ESPACIADOR DE PIÑÓN DEL ROTOR P/MOTOR NEUMATICO INGERSOLL',
            '173408' => 'PLACA TRASERA P/MOTOR NEUMATICO INGERSOLL',
            '173409' => 'PLACA FRONTAL P/MOTOR NEUMATICO INGERSOLL',
            '173410' => 'KIT ENGRANAJE DWE4314/4336-T1 P/AMOLADORA DEWALT',
        ];

        Tenant::query()->each(function (Tenant $tenant) use ($items): void {
            foreach ($items as $codigo => $nombre) {
                Item::query()->updateOrCreate(
                    ['tenant_id' => $tenant->id, 'codigo' => (string) $codigo],
                    ['nombre' => $nombre],
                );
            }
        });
    }
}
